config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'messages#index'

  resource :messages

  post 'pusher/auth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'User', foreign_key: 'recipient_id'

  validates_presence_of :sender_id, :recipient_id, :content
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :trackable,
         :validatable

  validates_presence_of :first_name, :last_name

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                       :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,
                                                              :last_name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @users = user_signed_in? ? User.where.not(id: current_user.id) : User.all
  end

  def show
    @messages = Message.where('(sender_id = :current_user AND recipient_id = :opposite_user) OR (sender_id = :opposite_user AND recipient_id = :current_user)', current_user: current_user.id, opposite_user: params[:recipient]).order('created_at ASC')
    @message = Message.new
  end

  def create
    @message = Message.new message_params
    trigger_message! if @message.save
  end

  private

  def message_params
    params.require(:message).permit(:content, :recipient_id)
                            .merge(sender_id: current_user.id)
  end

  def trigger_message!
    Pusher.trigger(params[:channel], 'message', {
      sender: @message.sender.name,
      sender_id: @message.sender_id,
      content: @message.content,
      timestamp: @message.created_at.to_formatted_s(:short)
    })
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  def auth
    if user_signed_in?
      response = Pusher.authenticate(params[:channel_name], params[:socket_id])
      render json: response
    else
      render text: 'Forbidden', status: '403'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def channel_name(message)
    "private-channel-#{message.sender.id}_#{message.recipient.id}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeChat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.pusher.com/3.2/pusher.min.js' %>
  </head>
  <body>
    <div class="navigation">
      <div class="container">
        <%= render 'shared/navigation' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="row <%= 'gray-background' unless message.sender == current_user %> message-container">
  <div class="column column-10">
    <small><%= message.sender == current_user ? 'You' : message.sender.name %></small>
  </div>
  <div class="column column-75">
    <small><%= message.content %></small>
  </div>
  <div class="column column-15 text-right">
    <small><%= message.created_at.to_formatted_s(:short) %></small>
  </div>
</div>

app/views/messages/_message_json.html.erb
<div class="row <%= 'gray-background' unless data.sender == current_user.name %> message-container">
  <div class="column column-10">
    <strong><%= data.sender == current_user.name ? 'You' : sender %></strong>
  </div>
  <div class="column column-75">
    <small><%= data.message %></small>
  </div>
  <div class="column column-15 text-right">
    <small><%= data.timestamp %></small>
  </div>
</div>

app/views/messages/create.js.erb
<% if @message.valid? %>
  $('#message_content').val('');
<% else %>
  $('#message_content').focus();
<% end %>

app/views/messages/index.html.erb
<% if @users.count.zero? %>
  <div class="row margin-top-20">
    <div class="column">
      There's no users that you can chat with.
    </div>
  </div>
<% else %>
  <div class="row margin-top-20">
    <div class="column">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td>
                <%=
                  link_to_if user_signed_in?, 'Chat Now', messages_path(recipient: user.id) do
                    link_to 'Chat Now', new_user_session_path
                  end
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/messages/show.html.erb
<div class="container margin-top-20" id="messages-container">
  <% if @messages.count.nil? %>
    <div class="row margin-top-20">
      <div class="column">No messages. Send your first message!</div>
    </div>
  <% else %>
    <% @messages.each do |message| %>
      <%= render 'message', message: message %>
    <% end %>
  <% end %>
</div>
<div class="row margin-top-20">
  <%= form_for @message, html: { class: 'column', id: 'message-form' }, remote: true do |f| %>
    <%= f.hidden_field :recipient_id, value: params[:recipient] %>
    <%= hidden_field_tag :channel, channel_name(@messages.first) %>
    <%= f.text_area :content, placeholder: 'Enter your text message here' %>
    <%= f.submit 'Send' %>
  <% end %>
</div>

<script type="text/javascript">
  var pusher = new Pusher('357cff67e138317ed474', {
    cluster: 'ap1',
    authEndpoint: '/pusher/auth',
    auth: {
      headers: {
        'X-CSRF-Token': "<%= form_authenticity_token %>"
      }
    },
    encrypted: true
  });

  var channel = pusher.subscribe("<%= channel_name(@messages.first) %>");
  channel.bind('message', function(data) {
    if(data.sender_id == "<%= current_user.id %>") {
      $('#messages-container').append('<div class="row message-container">' +
        '<div class="column column-10">' +
          '<small>You</small>' +
        '</div>' +
        '<div class="column column-75">' +
          '<small>' + data.content + '</small>' +
        '</div>' +
        '<div class="column column-15 text-right">' +
          '<small>' + data.timestamp + '</small>' +
        '</div>' +
      '</div>');
    } else {
      $('#messages-container').append('<div class="row gray-background message-container">' +
        '<div class="column column-10">' +
          '<small>' + data.sender + '</small>' +
        '</div>' +
        '<div class="column column-75">' +
          '<small>' + data.content + '</small>' +
        '</div>' +
        '<div class="column column-15 text-right">' +
          '<small>' + data.timestamp + '</small>' +
        '</div>' +
      '</div>');
    }
  });
</script>

app/views/shared/_navigation.html.erb
<div class="row">
  <div class="column column-15">
    <%= link_to 'Simple Realtime Chat', root_path %>
  </div>
  <div class="column column-15 column-offset-70">
    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, class: 'button button-outline float-right', method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, class: 'button float-right' %>
    <% end %>
  </div>
</div>